name: ros2-pibot-motor-fabolhak
version: '0.1'
summary: ROS2 Motor module for my PiBot
description: |
  This package provides the hardware driver to the PiBots motor.

confinement: devmode
base: core18

parts:
  ros2-motor-driver:
    plugin: colcon
    source: .
    source-branch: master
    colcon-rosdistro: dashing
    colcon-source-space: pibot_motor
    stage-packages: [ros-dashing-ros-core,python3-numpy,libblas3] # python-rpi.gpio,python3-rpi.gpio,,


apps:
  run:
    command: opt/ros/dashing/bin/ros2 run ros2_pibot_motor service
    plugs:
       - network
       - network-bind

architectures:
  - build-on: amd64
