name: ros2-pibot-motor-fabolhak
version: '0.1'
summary: ROS2 Motor module for my PiBot
description: |
  This package provides the hardware driver to the PiBots motor.

confinement: devmode
base: core18

parts:
  gpio:
    plugin: python
    python-version: python3
    python-packages: [RPi.GPIO]

  ros2-motor-driver:
    plugin: colcon
    source: .
    source-branch: gpio  setup:
    plugin: python
    python-version: python3
    python-packages: [RPi.GPIO]
    colcon-rosdistro: dashing
    colcon-source-space: pibot_motor
    stage-packages: [ros-dashing-ros-core,python3-numpy,libatlas3-base,libblas3] 


apps:
  run:
    command: opt/ros/dashing/bin/ros2 run ros2_pibot_motor service
    plugs:
       - network
       - network-bind
       - gpio
       - gpio-memory-control
       - hardware-observe

architectures:
  - build-on: arm64
