name: ros2-pibot-motor-fabolhak
version: '0.1'
summary: ROS2 Motor module for my PiBot
description: |
  This package provides the hardware driver to the PiBots motor.

confinement: devmode
base: core18

parts:

  ros2-motor-driver:
    plugin: colcon
    source: .
    source-branch: master
    colcon-rosdistro: dashing
    colcon-source-space: pibot_motor
    stage-packages: [python3-rpi.gpio,ros-dashing-core]

apps:
  run:
    command: opt/ros/dashing/bin/ros2 run ros2_pibot_motor service

architectures:
  - build-on: arm64
