name: ros2-pibot-motor-fabolhak
version: '1.1'
summary: ROS2 Motor module for my PiBot
description: |
  This package provides the hardware driver to the PiBots motor. Please read the [Readme](https://github.com/fabolhak/ros2_pibot_motor/blob/master/README.md) for usage instructions.
license: Apache-2.0

confinement: strict
base: core18
grade: stable

parts:
  ros2-motor-driver:
    plugin: colcon
    source: .
    source-branch: master
    colcon-rosdistro: dashing
    colcon-source-space: pibot_motor
    stage-packages: [ros-dashing-ros-core,libblas3,liblapack3]
      
  gpio-lib:
    plugin: python
    python-version: python3
    python-packages: [RPi.GPIO]

apps:
  run:
    command: opt/ros/dashing/bin/ros2 run ros2_pibot_motor service
    environment: 
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
    plugs:
       - network
       - network-bind
       - gpio-memory-control
       - hardware-observe

architectures:
  - build-on: arm64
